### ISSUE TITLE
For squeezenet, Softmax layer giving incorrect results

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#364] opened 2018-02-23 14:59 UTC
I'm tying to implement squeeze net using ARM ComputeLibrary. Layers in squeeze net are in folllowing order.
InputLayer
ConvLayer
ReLuLayer
MaxpoolingLayer
............
Avgpooling2DLayer
SoftmaxLayer
OutputLayer

SoftmaxLayer takes 3D Tensor as input from `AvgPooling2DLayer`. But  SoftmaxLayer gives incorrect output even i use shapes of `src` and `dst` tensors as  `TensorShape( 1U, 1U, 1000U)`.  I've attached the stand alone softmaxlayerTestsetup, softmaxInput, softmaxOutput, softmaxExpectedOutput.
[softmaxOutput](https://github.com/ARM-software/ComputeLibrary/files/1752150/SoftMax_1.txt)
[softmaxInput](https://github.com/ARM-software/ComputeLibrary/files/1752151/SoftMax_0.txt)
[softmaxExpectedOutput](https://github.com/ARM-software/ComputeLibrary/files/1752153/softmax_0.txt)
[softmaxlayerTestsetup](https://github.com/ARM-software/ComputeLibrary/files/1752154/sftm.txt)

Could you take a look into this and let us know if you face the same error or are we missing anything here?

Note: We have used the latest armcompute library.

Thanks in advance.

**Comment by GeorgeARM** [comment] 2018-02-23 15:03
Hello @nhkrishna,
Can you call `Flatten` or `Reshape` before calling `Softmax`?
Something like this [here](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_squeezenet.cpp#L172).

**Comment by GeorgeARM** [comment] 2018-02-26 13:51
@nhkrishna Is this resolved?

**Comment by GeorgeARM** [comment] 2018-03-06 16:43
Closing the issue as we cannot reproduce. Reopen if needed.

**Closed by GeorgeARM** 2018-03-06 16:43 UTC

**Comment by nhkrishna** [comment] 2018-12-26 12:59
Hi @GeorgeARM 

I have tried the above method(Introducing flatten before doing softmax operation to change the input Tensor shape from 3D to 1D), its giving expected results. But still i don't understand why softmax operation for 3D input and 3D output is not working for this particular case. 
And also tried channel wise softmax operation #401, where the permuted input and outputs are in 3D format and its giving correct values.
Could you please elaborate why flatten is needed in this case?
 
Thanks,
Hari
