### ISSUE TITLE
bad_alloc error at benchmark test with GLES

### ISSUE THREAD

**Issue by daeinki** [ARM-software/ComputeLibrary#397] opened 2018-03-28 03:50 UTC
Hi,

I have tested benchmark application and faced with bad_alloc error at GC/MobileNetBatchNormalizationLayer test case.

**arm_compute_version=v18.03 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'debug': '0', 'os': 'linux', 'Werror': '0'} Git hash=unknown**

**Operating System: Linux**

Expect result is that all test cases should be passed but one crash happended.
Executed 562 test(s) (561 passed, 0 expected failures, 0 failed, 1 crashed, 0 disabled) in 0 second(s)

You can refere to below benchmake logs,
-----------------------------------------------------------------------------------------------------------------
#./arm_compute_benchmark --filter='GC/.*' ./data/
Version = arm_compute_version=v18.03 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'debug': '0', 'os': 'linux', 'Werror': '0'} Git hash=unknown
Seed = 1570020356
Iterations = 1
Threads = 1
Dataset mode = PRECOMMIT
Running [7536] 'GC/MobileNetBatchNormalizationLayer@In=112x112x32:Out=112x112x32:Mean=32:Variance=32:Beta=32:Gamma=32:Epsilon=0.001:ActivationInfo=BOUNDED_RELU:DataType=F16:Batches=1'
ERROR: std::bad_alloc
-- snip --
Executed 562 test(s) (561 passed, 0 expected failures, 0 failed, 1 crashed, 0 disabled) in 0 second(s)

**Comment by AnthonyARM** [comment] 2018-04-03 17:51
Hi,
What platform is this on ? I'm afraid we can't reproduce the issue
`bad_alloc` usually means the platform is running out of memory. (Could you please check if that's the case? )

**Comment by daeinki** [comment] 2018-04-19 02:04
Hi, sorry for late.

I used Tizen platform[1].

I guess that GLES didn't work correctly. With arm_compute_benchmark I had several tests filtering various operators but in all cases, the first trying failed.

The version of MALI DDK I used is r12p0. Is there required version of MALI DDK for the use of GLES? 

Thanks.

[1] https://www.tizen.org/

**Comment by AnthonyARM** [comment] 2018-04-19 07:25
The warning is only referring to the prebuilt binaries. If you build the library yourself with the same toolchain then it should work.

What GPU are we talking about ? Is it Midgard (T6xx T7xx T8xx) or Bifrost (G7x) ?
All you need is a working GLES compute shader driver, have you successfully run other GLES compute applications on this platform ?

By the way if you've got OpenCL available I would recommend using it instead of GLES: it is much more mature, faster and has more features.

**Comment by daeinki** [comment] 2018-04-19 08:46
The GPU I used is T760 and other GLES apps work well on my platform.

And I found out the use of GLES requires huge memory,
write(1, "\33[0;32mRunning [9205] 'GC/Softma"..., 71Running [9205] 'GC/SoftmaxLayer@Shape=256x10x2:DataType=F16'
) = 71
brk(0x9a7000)                           = 0x9a7000
mmap2(NULL, 4293758976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 4293894144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)

4293758976 = about 4096MB. :(
Is it true to require more than 4GB?

I just wanted to check GLES also works. :)

Thanks.

**Comment by mpekatsoula** [comment] 2018-09-20 11:35
@daeinki Is this issue still present in v18.08? We cannot reproduce this in our side so please make sure your platform has enough memory.

Closing, reopen if needed.

**Closed by mpekatsoula** 2018-09-20 11:35 UTC
Labels: Question
