### ISSUE TITLE
Tensorflow with compute lib

### ISSUE THREAD

**Issue by peter73421** [ARM-software/ComputeLibrary#286] opened 2017-11-16 13:19 UTC
I have a question is there some available instructions how to enable tensorflow with arm compute library?

**Comment by GeorgeARM** [comment] 2017-12-01 17:51
Hello @peter73421,

Compute Library has not been integrated to tensorflow yet. This is a duplicate of #7 .
You can find more information there.

**Comment by GeorgeARM** [comment] 2017-12-01 17:51
Closing. Duplicate of #7

**Closed by GeorgeARM** 2017-12-01 17:51 UTC
