### ISSUE TITLE
CLConvolutionLayer global variable

### ISSUE THREAD

**Issue by ghost** [ARM-software/ComputeLibrary#270] opened 2017-10-30 15:09 UTC
How can I make variables of type CLConvolutionLayer global? I have forward function which takes input and returns output and I don't want to reinitialize CLConvolutionLayer variable each time in forward function, but when I make CLConvolutionLayer inside function scope, as global variable, program crashes.

**Comment by morgolock** [comment] 2018-08-01 11:33
Hi @ghost 

Please share the code which is crashing and I'll try to find what the problem is.

I'll close the issue, if you still have the problem please reopen and provide the information mentioned above.

**Closed by morgolock** 2018-08-01 11:33 UTC
Labels: Help wanted
