### ISSUE TITLE
Output mismatch in Warp affine kernel

### ISSUE THREAD

**Issue by manjunathahg** [ARM-software/ComputeLibrary#475] opened 2018-06-28 11:29 UTC
**Output of 'strings libarm_compute.so | grep arm_compute_version':** arm_compute_version.embed

**Platform:** ACL NEON

**Operating System:** Linux 64 bit

**Problem description:** Hi Sir
We are trying to execute Warp affine kernel in arm compute library on ACL NEON platform and facing below mentioned problems:
	a) Output does not match with reference(C model) in case of undefined border mode and Bilinear interpolation combination
	b) Output doest not match with reference(C model) in case of dimension 16x16 or lesser than that with undefined border mode and nearest neighbour interpolation type. 
Attaching the sample workspace and logs for reference.

Please let us know your inputs in resolving the issue.
Thanks in advance

[neon_warpaffine_test .txt](https://github.com/ARM-software/ComputeLibrary/files/2145043/neon_warpaffine_test.txt)
[warpaffine_log.txt](https://github.com/ARM-software/ComputeLibrary/files/2145067/warpaffine_log.txt)
[warpAffine_ref_output.txt](https://github.com/ARM-software/ComputeLibrary/files/2145069/warpAffine_ref_output.txt)

**Comment by gmiodice** [comment] 2018-06-29 08:55
maybe duplicate of #421

**Comment by morgolock** [comment] 2018-08-13 12:33
Hi @manjunathahg 

It's ok to expect mismatches between openvx reference implementation and ACL when using border mode `undefined`. Openvx reference implementation doesn't change the value of the output buffer in this case (because the pixels are not valid) and ACL would write 0. 

![warpundefined](https://user-images.githubusercontent.com/5577511/44031855-353a989e-9efd-11e8-8245-3e8b8d6af7b5.png)

Quoting the VX 1.2 spec:

>Valid Pixels - All output pixels of an OpenVX function are considered valid by default, unless their
>calculation depends on input pixels that are not valid. 
>An input pixel is not valid in one of two situations:
>The pixel is outside of the image border and the border mode in use is VX_BORDER_UNDEFINED
>The pixel is outside the valid region of the input image.

**Closed** 2018-08-14 13:46 UTC
Labels: Question
