### ISSUE TITLE
iOS build support

### ISSUE THREAD

**Issue by Realitian** [ARM-software/ComputeLibrary#201] opened 2017-08-15 16:32 UTC
Hi, 
This library is support to build for iOS?
How I can build it for iOS(iphone)?

**Comment by oscarbg** [comment] 2017-08-16 08:44
+1

**Comment by mpflanzer** [comment] 2017-08-16 09:16
It should be no problem to use the library under iOS. Building it is a bit tricky though. You could try to configure scons so that it sets the correct flags to compile for iOS. But I guess it's easier to create an XCode project. I just tried it myself and was able to successfully build the NEON part.

Steps to reproduce:
- Create project for macOS static library
- Change deployment target to iOS
- Add all header and source files
- Set the correct header paths (only necessary if `arm_compute` is not in the same directory as the project)
- Build the library

The only problem with this approach is that there is a bug in XCode 8 due to which the compilations fails. The bug has been fixed in XCode 9 which is currently available as beta version.

**Comment by mo-morikawa** [comment] 2017-09-06 03:47
@mpflanzer  I started buidling it for iOS. Should I add the files in the src directory, or only those in the arm_compute directory? Should I remove the header files created by the Xcode project, or which files should I replace them with? Thanks in advance!

**Comment by mpflanzer** [comment] 2017-09-14 07:02
Apologies for my late reply. You need to add the files from our `src` directory to "Compile source" and the header files from `arm_compute` to the "Headers" section. (Both section are under the "Build phases" tab in the target properties.

If Xcode generates any files itself they shouldn't be required.

**Comment by AnthonyARM** [comment] 2017-10-03 17:51
@y22ma : It's generated by SCons [here](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/SConscript#L114)

Then included in Core [ere](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/src/core/Utils.cpp#L40)

**Comment by G-mel** [comment] 2017-10-03 18:07
when building this on xcode, in the file `src/runtime/OMP/OMPScheduler.cpp` on line 67, the line 
```kernel->run(max_window);```
 gives the error `Too few arguments to function call, expected 2, have 1` and is requires a `ThreadInfo` pointer as a second argument. How could I fix this?

**Comment by AnthonyARM** [comment] 2017-10-03 18:35
You found a bug: we forgot to update the OMP Scheduler following a change of interface in IKernel
We'll fix that in the next maintenance release (The code should look something like [that](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/src/runtime/CPP/CPPScheduler.cpp#L180) )
In the meantime could you compile with `cppthreads=1` and use the CPPScheduler instead ?

**Comment by G-mel** [comment] 2017-10-03 18:42
@AnthonyARM Ah okay.

And sorry, how would I compile with `cppthreads=1`? Would it be in the `Other C++ Flags` section on the xcode project's build settings?

**Comment by AnthonyARM** [comment] 2017-10-03 18:47
I'm not sure about XCode: the only thing SCons seems to do is add "CPPScheduler.cpp" to the list of files to build: [SConsript](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/SConscript#L146)
So maybe remove OMPScheduler.cpp from your project and keep CPPScheduler.cpp ?

**Comment by G-mel** [comment] 2017-10-04 14:43
@mpflanzer I'm coming across an error: `Unknown register name 'q0' in asm` on line 229 in `arm_compute/core/NEON/kernels/assembly/merges/a64_merge_float_12x8.hpp` when compiling it on xcode-beta 9 on an arm64 architecture. What steps did you go through in xcode to get it to fully compile?

**Comment by y22ma** [comment] 2017-10-17 20:05
It looks like ARMv8 (arm64 in XCode) has very different instruction sets. Q registers are not really accessible for ARCH64. Probably will need to rewrite the assembly in that file.

**Comment by y22ma** [comment] 2017-10-27 15:24
Just an update on this, changing qX registers to vX worked in that file.

**Comment by AnthonyARM** [comment] 2017-10-27 17:12
You're correct, we should be using `v` instead of `q`
We're in the process of fixing this.

**Comment by y22ma** [comment] 2017-10-30 04:07
Thanks! The performance though is underwhelming. I compiled with -03 and -ftree-vectorize as SDCon script does when debug=0, but it actually ends up to be slower than OpenCV routines for things like fast corner detection.

**Comment by morgolock** [comment] 2018-08-14 10:03
Closing this issue because the library has been built for iOS successfully. Feel free to open another thread regarding the performance.

**Closed by morgolock** 2018-08-14 10:03 UTC
Labels: Help wanted

**Comment by pzoltowski** [comment] 2025-07-03 04:28
shouldn't README then be updated to state iOS is also supported?

**Comment by morgolock** [comment] 2025-07-03 12:52
Hi @pzoltowski 

We haven't done it because we don't build/test the library on iOS in our pipeline. We only do it for macOS. While we don't officially state support for iOS, the library should work without problems on these systems.
