### ISSUE TITLE
the performance of computeLibrary on armv7a

### ISSUE THREAD

**Issue by szcv** [ARM-software/ComputeLibrary#128] opened 2017-06-08 04:21 UTC
Does anybody knows how to use computeLibrary to accelerate machine learning such as compute hog feature with computeLibrary? Who can give some examples ?there would be helpful,thanks.
And there is another problem.When I tested convolution with computeLibrary and opencv library,I found that it was even slower while using computeLibrary than using opencv library.So it really confused me.

**Comment by AnthonyARM** [comment] 2017-06-08 07:36
There are some examples in the `examples` folder, you can also have a look at the other issues here on Github for more.
The compute library should be much faster than OpenCV, make sure you compile with `asserts=0` and `debug=0` when you want to measure time.
Don't forget to set your CPU to performance mode and [force_number_of_threads()](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_c_p_p_scheduler.xhtml#ae9dc1846ff1612778bbac85d46344aef) to match the number of big cores you have on your system (Assuming this is a big LITTLE configuration)

**Comment by AnthonyARM** [comment] 2017-06-08 07:37
Regarding HOG: we will publish a blog post about how to use HOG / SVM in a few weeks.

**Comment by szcv** [comment] 2017-06-08 08:57
Hi  AnthonyARM:
      Thanks for your suggestion.I have tried your advice, when I compile ComputeLibrary with :`scons Werror=1 -j8 debug=0 asserts=0 neon=1 opencl=0  os=linux build=native  arch=armv7a`  ,it has following problems:
`In file included from ./arm_compute/core/Window.h:334:0,
                 from ./arm_compute/core/Helpers.h:32,
                 from src/core/ITensor.cpp:27:
./arm_compute/core/Window.inl: In member function 'void arm_compute::ITensor::copy_from(const arm_compute::ITensor&)':
./arm_compute/core/Window.inl:43:27: error: array subscript is above array bounds [-Werror=array-bounds]
     _dims[dimension] = dim;
                           ^
./arm_compute/core/Window.inl:43:27: error: array subscript is above array bounds [-Werror=array-bounds]
     _dims[dimension] = dim;
                           ^
cc1plus: all warnings being treated as errors
scons: *** [build/arm_compute/src/core/ITensor.o] Error 1
scons: building terminated because of errors.`

When I change compile command as:`scons Werror=0 -j8 debug=0 asserts=0 neon=1 opencl=0  os=linux build=native  arch=armv7a` ,the compilation process finished.And I use the 	
generate so files to compile my project to test convolution time between CompileLibrary and opencv library. The result was the same as before.
Are there any compile options that I didn't make correctly?

**Comment by szcv** [comment] 2017-06-08 12:19
@AnthonyARM 
   By the way, my code runs on arm Cortex-A7  .
   Appreciate for your help.

**Comment by AnthonyARM** [comment] 2017-06-13 12:12
Your compilation options look good, the problem might come from your platform configuration: if you have a big LITTLE platform you need to make sure to disable the small cores, and set the big cores to the maximum frequency, etc.

**Comment by qingswu** [comment] 2017-07-07 04:47
Any update on the HOG/SVM example?

**Comment by gmiodice** [comment] 2017-07-07 07:34
Hi @qingswu ,

we are in the process of writing a blog post which will explain step by step how to use OpenCV to get the model and how to use our HOG/SVM for implementing a traditional computer vision pipeline for doing object detection.

We will let you know once will be published.

Thanks

**Comment by i7clock** [comment] 2018-06-25 09:12
Hi @AnthonyARM,

where can I find the blog on HOG?

Best wishes

**Comment by GeorgeARM** [comment] 2018-10-15 14:46
Closing as duplicate of #129

**Closed by GeorgeARM** 2018-10-15 14:46 UTC
Labels: Question
