### ISSUE TITLE
how to use NEIm2ColKernel::configure(.., std::pair<unsigned int, unsigned int> convolved_dims, ..)

### ISSUE THREAD

**Issue by xlxulin1** [ARM-software/ComputeLibrary#63] opened 2017-04-24 09:32 UTC
void NEIm2ColKernel::configure(const ITensor *input, ITensor *output, std::pair<unsigned int, unsigned int> convolved_dims, const PadStrideInfo &conv_info, bool has_bias)
I don't understand the parameter (std::pair<unsigned int, unsigned int> convolved_dims) of this function.
Can someone explain it?
For example, the input is 300x300, kernel is 3x3. pad x/y =0, stride x/y = 1;

    const TensorShape shape(300, 300, 1);
    const TensorShape shape_im2col(3*3, 298 * 298, 1);

    output.allocator()->init(TensorInfo(shape_im2col, 1, DataType::F32));
    input.allocator()->init(TensorInfo(shape, 1, DataType::F32));

    NEIm2ColKernel im2Col;

    //how is this paramete??????????
    std::pair<unsigned int, unsigned int> pair(3, 3);
    PadStrideInfo padStrdInfo(1, 1, 0, 0);

    im2Col.configure(&input, &output, pair padStrdInfo, false);

how does this parameter effect on the output??

**Comment by GeorgeARM** [comment] 2017-04-24 11:48
Hello @xlxulin1,

I can understand your confusion. In convolved_dims pair you should pass the width and height of the output tensor of the convolution. We use it inside the kernel to configure the execution window.
So for your example 300x300 with 0 pad and stride 1 this pair should be 298,298.

**Comment by xlxulin1** [comment] 2017-04-24 11:52
Hello @GeorgeARM ,

Thanks a lot, I'll check it.
Except this parameter, is there any other mistakes in this codes.

**Comment by GeorgeARM** [comment] 2017-04-24 12:08
I can't notice something else at the moment @xlxulin1 .
Give it a try! In case your issue is resolved you can close #64 as looks like a duplicate of this one.

**Comment by xlxulin1** [comment] 2017-04-24 12:53
Thanks @GeorgeARM.
It works, I got the right result. But I want to know is there any way to control transposition in this function.
the normal result:
0, 1, 2, 10, 11, 12, 20, 21, 22;
1, 2, 3, 11, 12, 13, 21, 22, 23;
2, 3, 4, 12, 13, 14, 22, 23, 24;
10, 11, 12, 20, 21, 22, 30, 31, 32;
11, 12 ,13, 21, 22, 23, 31, 32, 33;
12, 13, 14, 22, 23, 24, 32, 33, 34;

But I'd like to get this:
0, 1, 2, 10, 11, 12;
1, 2, 3, 11, 12, 13;
2, 3, 4, 12, 13, 14;
10, 11, 12, 20, 21, 22;
11, 12 ,13, 21, 22, 23;
12, 13, 14, 22, 23, 24;
20, 21, 22, 30, 31, 32;
21, 22, 23, 31, 32, 33;
22, 23, 24, 32, 33, 34;

**Closed** 2017-04-26 13:11 UTC
