### ISSUE TITLE
High memory consumption for Convolution Layer

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#54] opened 2017-04-19 12:57 UTC
Hello

I was trying out neural network creation using the ARM Compute Neon Library.

I have used below configuration parameters for Convolution Layer:
 conv0.configure(&src, &weights0, &biases0, &out_conv0, PadStrideInfo(2,2,3,3,DimensionRoundingType::FLOOR));

Input dimensions are as below (all data type float):
weights - [64*7*7*3];
biases - [64];
input image - [448*448*3];

Output dimesions (all data type float):
[224x224x64]

The expected total memory consumption should be less than ~20MB
However, the memory consumption noted after execution of above  conv0.configure is >250MB

Could you clarify whether this high memory usage is expected.
(As memory is main constraint on neural n/ws - I have posed this query).

Thanks
kamrao

**Comment by mkamrao** [comment] 2017-04-19 12:59
typo in above query: please read as below
weights - [64 x 7 x 7 x 3];
biases - [64];
input image - [448 x 448 x 3];
 
thanks

**Comment by AnthonyARM** [comment] 2017-04-19 13:10
- Are you using the latest release ? (17.04)
- Are you using auto padding or accurate padding ( [documentation](https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_6_1_padding_and_border) )
- Which function are you using ? (Neon or OpenCL ?)

**Comment by mkamrao** [comment] 2017-04-19 17:00
Hello

>>Are you using the latest release ? (17.04)
Yes,  i am using latest release(17.04)

>>Are you using auto padding or accurate padding ( documentation )
I am not setting any type of padding

>>Which function are you using ? (Neon or OpenCL ?)
I am using the Neon APIs.

Let me know, if any further information is needed.

Thanks
Kamrao

**Comment by developer-compute** [comment] 2017-04-19 22:19
Can you please post the code where you initialize, configure, allocate, fill the tensors / functions so that we can try to reproduce on our end?


________________________________

**Comment by mkamrao** [comment] 2017-04-20 06:15
Hello

Please find the code that was used, pasted below:
-------------------------------------------------------------------------------------------------------------------
    constexpr unsigned int width_src_image  = 448;
    constexpr unsigned int height_src_image = 448;
    constexpr unsigned int ifm_src_img      = 3;

    const TensorShape src_shape(width_src_image, height_src_image, ifm_src_img);
    src.allocator()->init(TensorInfo(src_shape, 1, DataType::F32));

    // Initialize tensors of conv0
    constexpr unsigned int kernel_x_conv0 = 7;
    constexpr unsigned int kernel_y_conv0 = 7;
    constexpr unsigned int ofm_conv0      = 64;
    
    constexpr unsigned int kernel_x_out = 224;
    constexpr unsigned int kernel_y_out = 224;
    
    const TensorShape weights_shape_conv0(kernel_x_conv0, kernel_y_conv0, src_shape.z(), ofm_conv0);
    const TensorShape biases_shape_conv0(weights_shape_conv0[3]);
    const TensorShape out_shape_conv0(kernel_x_out, kernel_y_out, weights_shape_conv0[3]);
    
    weights0.allocator()->init(TensorInfo(weights_shape_conv0, 1, DataType::F32));
    biases0.allocator()->init(TensorInfo(biases_shape_conv0, 1, DataType::F32));
    out_conv0.allocator()->init(TensorInfo(out_shape_conv0, 1, DataType::F32));

    /* -----------------------End: [Initialize tensors] */

    /* [Configure functions] */

    conv0.configure(&src, &weights0, &biases0, &out_conv0, PadStrideInfo(2,2,3,3,DimensionRoundingType::FLOOR));
    /* -----------------------End: [Configure functions] */

    
    /* [Allocate tensors] */

    // Now that the padding requirements are known we can allocate the images:
    src.allocator()->allocate();
    weights0.allocator()->allocate();
    biases0.allocator()->allocate();
    out_conv0.allocator()->allocate();
-------------------------------------------------------------------------------------------------------------------

The high memory consumption (>250MB) is noted immediately after conv0.configure in above code.
Hence, allocate or filling the tensors may not be needed.

Thanks

**Comment by mpflanzer** [comment] 2017-04-20 11:10
Thanks for providing your code. We have been able to reproduce the problem. The high memory consumption is caused by an error in the padding calculation for intermediate tensors in the convolution layer function.

The issue will be fixed in the next release.

**Comment by mkamrao** [comment] 2017-04-20 11:50
Hello

Thank you. When is the release with fix expected.

Kamrao

**Comment by sherwin29** [comment] 2017-04-23 13:47
It seems that this memory issue also happens when calling OpenCL Api.
It works fine when trying to initialize, configure, and allocate 1 or 2 conv layers(with relu/pool/norm) which has the correct results; while for configuring, allocating more layers repeatedly, the error occurs:

ERROR in void arm_compute::Window::validate() const ./arm_compute/core/Window.inl:73: _dims[i].end() <= _dims[i].start() Illegal seek
!!!!!!!!!!!!!!!!!!!!!!!!!!!

right after calling layer configure function.

is there a way to share memory usage or manually free some of the buffer no long used?

**Comment by mkamrao** [comment] 2017-05-01 11:49
Hi...

Any update on when the next release with the fix is expected. Thanks

Kamrao

**Comment by AnthonyARM** [comment] 2017-05-03 12:49
Sorry for the wait.
Hopefully by the end of the week.

**Comment by GeorgeARM** [comment] 2017-05-04 11:55
Hello @mkamrao,
Fix has been applied in v17.05 release. Can you check if this solves your issue?

**Closed** 2017-05-04 13:04 UTC
Labels: Fixed in next release, Help wanted

**Comment by mkamrao** [comment] 2017-05-10 08:47
Hello 

Memory consumption is better now (~70MB), but higher than expected. Is this due to memory padding? Can this be reduced further? Thanks 

kamrao
