### ISSUE TITLE
NV12 Image format not giving proper output with NEChannelCombine 

### ISSUE THREAD

**Issue by ganashree-rm** [ARM-software/ComputeLibrary#301] opened 2017-12-11 05:12 UTC
Hi,
When using NEChannelCombine to form NV12 format output for an image dimension of (18x18), I find that the second plane (UV interleaved buffer) of the output image is of inappropriate dimension (9x9) when printed using ITensor :: print () instead of (18x9). When I printed the output buffers manually I find that the last two columns contain zeros. Please let me know how to resolve this problem.
I have attached the sample testapp and the output obtained from it. 

[neon_channel_combine_nv12.txt](https://github.com/ARM-software/ComputeLibrary/files/1546581/neon_channel_combine_nv12.txt)
[output_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1546582/output_log.txt)

**Comment by AnthonyARM** [comment] 2017-12-11 09:31
Hi,
Thanks for reporting this bug, we'll include a fix in the next release of the library.

**Comment by ganashree-rm** [comment] 2017-12-11 09:47
Hi,
Thank you for the response.

**Comment by cristian-szabo-arm** [comment] 2017-12-12 09:37
Hi @ganashree-rm ,

I assume that you build the library in release mode with asserts disabled and so you were able run the ChannelCombine function by ignoring the assert conditions. If you try to enable asserts (or build in debug mode) you will notice that the 18x18 shape is not a valid input when the function runs.

The print function of the tensor does not support multiple channels so it cannot be used to print correctly the values of the second plane (UV).

The zeroes in the last columns of the shape are caused by an issue with the NEON implementation and we are currently working to fix it and provide you a workaround solution.

HTH,
Cris

**Comment by ganashree-rm** [comment] 2017-12-19 07:16
Hi @cristian-szabo-arm,
Thanks for the information on the print function of tensors.We have found that compute Library version (17.12)  has been released recently, just wanted to know if this includes the fix of the above reported issue. Could you provide your inputs on this?

**Comment by AnthonyARM** [comment] 2017-12-21 10:10
Yes, both the fix to the print function and channel combine should be included in the 17.12 release

**Comment by AnthonyARM** [comment] 2018-02-13 16:37
No update in a while, bug fixes have been released.
Closing ticket

**Closed by AnthonyARM** 2018-02-13 16:37 UTC
