### ISSUE TITLE
Question about arm mali gpu and qualcomm adreno gpu

### ISSUE THREAD

**Issue by 18810579179** [ARM-software/ComputeLibrary#552] opened 2018-09-30 01:22 UTC
HI

Thank you for your excellent work!

I have a question. I got Qualcomm Adreno 630 Gpu has L1 cache for read_only image object, which have better performance compared with buffer object. But ACL uses buffer object for storage, is any performance advantage to use buffer object compared to image object for mali GPU?

By the way, is there any other difference for mali GPU compared to Adreno GPU?

Thanks, Hope your reply soon

**Comment by GeorgeARM** [comment] 2018-10-15 15:05
Hello @18810579179,

Yes, using a read_only image object can lead to a better performance sometimes. At the moment we only use buffer objects but we are planning to investigate in supporting more types. I am not aware of the difference between an Adreno and a Mali GPU.

I will close this question as a duplicate of #539.

**Closed by GeorgeARM** 2018-10-15 15:05 UTC
Labels: Question
