### ISSUE TITLE
is there speed test result compare of ACL on armv8 and mali?

### ISSUE THREAD

**Issue by wl3b10s** [ARM-software/ComputeLibrary#471] opened 2018-06-25 06:52 UTC
I use the official 18.05 binary release and test on Galaxy S8+.

which has CPU 4xA72+4xA53 and GPU Mali-G72 , OS is Android 7.0

I test the graph_squeezenet_v1_1 and graph_lenet_aarch64 in examples folder.

the result show that running using OpenCL is much slower than NEON.  about 10times slower.

is that right? 

thanks.

**Comment by gmiodice** [comment] 2018-06-25 07:46
Hi @wl3b10s,

the results on OpenCL shouldn't be slower than NEON. How many times do you run your test? Are you evaluating the performance at maximum GPU frequency?

**Comment by psyhtest** [comment] 2018-06-25 08:39
Hi @wl3b10s ,

Your observation seems to be consistent with [Mali-G72 results reported elsewhere](https://discuss.96boards.org/t/comparison-between-hikey960-and-hikey970/5008). I suspect I know the [cause for regression](https://github.com/ARM-software/ComputeLibrary/pull/432#issuecomment-393699793) but I need to find some time to verify this (hopefully, this week).

**Comment by wl3b10s** [comment] 2018-06-26 00:59
thanks for both of your advice @gmiodice @psyhtest 

the following is my result on S8+ with target 0-3 set.

it seems:
0) with random data, the run on gpu is much faster than on cpu. but.
1) using GPU cost a lot of time for setup net compared to use neon.
2) why squeezenet with opengles crash?
3) seems that NEON implementation does not full use of multicore.  cpu usage by top is only about 25%. is there setting for more parallelization?

thanks.
(sorry for the format of the table)

Squeezenet_1_1 
Target                | NEON | CL | CL+HINT | ES
Setup                 | 850ms | 4.5s | 4.5s | Crash
20 times             | 0.527274 | 0.033252 | 0.047456 | Crash
                          0.374725 | 0.036539 | 0.035659 | terminate called after throwing an instance of 'std::out_of_range'
                          0.255672 | 0.033896 | 0.029453
                         0.213132 | 0.034212 | 0.031723
                         0.164106 | 0.031288 | 0.029938
                         0.140704 | 0.027858 | 0.02986
                        0.135897 | 0.023485 | 0.032228
                        0.13681 | 0.02841 | 0.037077
                        0.136942 | 0.023897 | 0.038216
                        0.136445 | 0.038706 | 0.034876
                       0.136712 | 0.034191 | 0.038322
                       0.136614 | 0.027378 | 0.039403
                       0.137018 | 0.027769 | 0.030809
                       0.139093 | 0.025985 | 0.031689
                       0.135974 | 0.029166 | 0.033596
                       0.136748 | 0.024768 | 0.035764
                       0.136417 | 0.02851 | 0.031509
                       0.136361 | 0.025796 | 0.033357
                       0.137693 | 0.022106 | 0.020068
                       0.136987 | 0.021603 | 0.020129

lenet
| NEON | CL | CL+HINT | ES
| 180ms | 980ms | 984ms | 850ms     ----------- setup time
0.023636 | 0.005597 | 0.006327 | 0.00288          ----Run 20 times
0.026862 | 0.005541 | 0.00607 | 0.003515
0.030615 | 0.004903 | 0.006013 | 0.003734
0.021369 | 0.004742 | 0.005988 | 0.003934
0.020625 | 0.005805 | 0.004095 | 0.004048
0.016351 | 0.007317 | 0.005102 | 0.004017
0.015044 | 0.006383 | 0.005452 | 0.004807
0.014074 | 0.006609 | 0.006565 | 0.003824
0.014844 | 0.006084 | 0.006648 | 0.003721
0.018525 | 0.005882 | 0.005761 | 0.004499
0.020562 | 0.006874 | 0.006033 | 0.003858
0.018585 | 0.006356 | 0.005591 | 0.005439
0.018538 | 0.007255 | 0.005447 | 0.003803
0.018226 | 0.007216 | 0.00561 | 0.004577
0.016974 | 0.006812 | 0.006273 | 0.004498
0.016443 | 0.00719 | 0.007326 | 0.005237
0.01709 | 0.007769 | 0.008436 | 0.003462
0.018675 | 0.00733 | 0.007413 | 0.004938
0.01762 | 0.006235 | 0.006959 | 0.003901
0.017748 | 0.007636 | 0.007979 | 0.00538

**Comment by gmiodice** [comment] 2018-06-26 08:44
Hi @wl3b10s,

thanks a lot for reporting your result. We are investigating on the GLES issue and will let you know as soon as possible. Looking at your table I see CL + HINT having in same cases worst performance than CL. This for me is strange because CL + HINT (called cl-tuner version) should always be faster or, in the worst case, having the same performance. if this happen it means probably the GPU frequency is not constant for the whole duration of the test.
I'd suggest to run your test and monitoring the GPU frequency as well. We will write a note in the documentation of the next release about this aspect for using properly the cl-tuner.

In the for what concerns the setup time do you build the library with embed_kernels=1?

thanks,
Gian Marco

**Comment by wl3b10s** [comment] 2018-06-26 09:11
i am afraid the .a I used is build with kernels.

"strings libarm_compute-static.a | grep arm_compute_version
arm_compute_version=v18.05 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'pmu': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'build_dir': 'android-arm64-v8a-neon-cl-gles', 'standalone': '0', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'os': 'android', 'Werror': '1'} Git hash=12ad439c2511cca35b36cabcd6b342feccf6f02b
"

**Comment by GeorgeARM** [comment] 2018-10-15 15:08
Hello @ghimiredhikura,

In your scons command you can set `benchmark_tests=1`, this should create binaries for each example with the prefix `benchmark_`. Then you can use the benchmarking framework infrastructure to benchmark each example.

e.g.
```
./benchmark_graph_squeezenet_v1_1 --iterations=10 --example_args="--target=cl,--type=f32" --instruments="wall_clock_timer_ms"

./benchmark_graph_squeezenet_v1_1 --iterations=10 --example_args="--target=neon,--threads=4,--type=f32" --instruments="wall_clock_timer_ms"
```

You can check all the common graph parameters [here](https://github.com/ARM-software/ComputeLibrary/blob/master/utils/CommonGraphOptions.h#L37) and you can check the instruments that you can use [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/framework/instruments/Instruments.cpp#L39).

**Comment by GeorgeARM** [comment] 2018-10-15 15:09
Closing issue. Reopen if needed.

**Closed by GeorgeARM** 2018-10-15 15:09 UTC
Labels: Performance, Question
