### ISSUE TITLE
convolution configure failure

### ISSUE THREAD

**Issue by joey2014** [ARM-software/ComputeLibrary#66] opened 2017-04-26 02:16 UTC
Test environment :
    android M+ arm_compute v17.04
in some case, create convolution failure, I provide two cases one is workable case and the other is failure case in attach code.
[test1.zip](https://github.com/ARM-software/ComputeLibrary/files/957020/test1.zip)

build the test sample:
aarch64-linux-android-g++ conv_test1.cpp -std=c++11 -I. -pie -o test1 -Lbuild -larm_compute

from debug: 
scaled_dimensions 1 ceil 2
conv_w 2(expect 1),conv_h 3(expect 2)
terminate called after throwing an instance of 'std::runtime_error'
  what():  in void arm_compute::NEConvolutionLayer::configure(const arm_compute::ITensor*, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&) src/runtime/NEON/functions/NEConvolutionLayer.cpp:73: Output shape does not match the expected one

Can you help check the issue?

**Comment by cyberfire** [comment] 2017-04-26 06:58
Please use DimensionRoundingType::FLOOR instead of DimensionRoundingType::CEIL.
Also, please create a new neconvlayer in the second case. As the neconvlayer.configure() in first case will have some side effect.

Thanks,

Haitao

**Comment by mpflanzer** [comment] 2017-04-26 09:39
Yes, @cyberfire is right. For your inputs and outputs you need to use `DimensionRoundingType::FLOOR`. (This is also the only mode that Caffe supports.)

Reconfiguring the convolution layer function shouldn't cause any problems as long the the tensors are not allocated between the two calls to `configure`.

**Comment by GeorgeARM** [comment] 2017-05-03 18:06
Assuming the issue is resolved! Closing! Reopen if required!

**Closed by GeorgeARM** 2017-05-03 18:06 UTC
Labels: Help wanted
