### ISSUE TITLE
uint8 quantized model runs slower than fp32 model

### ISSUE THREAD

**Issue by liamsun2019** [ARM-software/ComputeLibrary#987] opened 2022-07-12 07:51 UTC
Hi author，
I encountered a question while doing inference on cortex-A55 aarch64 with CpuAcc as the backend. There are 2 models , one is fp32 and the other one is uint8 quantized. My tests showed that fp32 ran even faster than the uint8 quantized one. Just curious why this would happen. Please refer to the attachment for the 2 models. In addition, both c++ parser mode and delegate mode have the same issue. ReduceFp32ToFp16 is set to True in my tests. Appreciate your suggestions. Thanks.
[test.zip](https://github.com/ARM-software/ComputeLibrary/files/9090768/test.zip)

**Comment by morgolock** [comment] 2022-07-29 14:01
Closing this as a duplicate of https://github.com/ARM-software/armnn/issues/667

**Closed by morgolock** 2022-07-29 14:01 UTC
Labels: Question
