### ISSUE TITLE
For MNIST, NormLayer is giving incorrect results

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#342] opened 2018-01-25 08:11 UTC
**I'm tying to implement MNIST Network using ARM ComputeLibrary. Layers in MNIST are in folllowing order.**
_InputLayer
ConvLayer
MaxpoolingLayer
ConvLayer
MaxpoolingLayer
FCLayer
ReLULayer
NormLayer
FCLayer
SoftmaxLayer
OutputLayer_

**The NormLayer takes input from the ReLU layer. But the NormLayer output mismatches with the expected result.**  I've attached the stand alone  test setup for NormLayer , NormLayer Input, NormLayer output,  NormLayer expected output.
[normExpected.txt](https://github.com/ARM-software/ComputeLibrary/files/1663055/normExpected.txt)
[normInput.txt](https://github.com/ARM-software/ComputeLibrary/files/1663056/normInput.txt)
[normOutput.txt](https://github.com/ARM-software/ComputeLibrary/files/1663057/normOutput.txt)
[normTestsetup.txt](https://github.com/ARM-software/ComputeLibrary/files/1663058/normTestsetup.txt)

Could you take a look into this and let us know if you face the same error or are we missing anything here?

Note: We have used the latest armcompute library.

Thanks in advance.

**Comment by nhkrishna** [comment] 2018-02-06 13:14
Is there any update on this ?

**Comment by GeorgeARM** [comment] 2018-02-06 13:46
Hello @nhkrishna,

I added your shapes as a test case in our internal testing and we didn't see any failures.
First looking at your code you don't need two `src` tensors.
Use a single one and pass it to configure. Then allocate src and use `copy_n` or `memcpy` to copy 500 elements only to you `src` tensor from your `relu` buffer. The starting position to copy inside your `src` tensor should be:
```src->info()->buffer() + src->info()->offset_first_element_in_bytes```
Hope this helps.
If it still fails post the update code here as a comment

**Comment by nhkrishna** [comment] 2018-02-13 06:06
Hello @GeorgeARM,

We have changed the wrapper as per your suggestion and we are still seeing the same issue . We 've attached the wrapper for your reference.

We are running this setup on rpi 3. Could you let us know on which platform did you run and share us your test setup or make commands. Could you let us know whether the norm outputs that you have got are matching with the values in normExpected.txt.

[normTestsetup.txt](https://github.com/ARM-software/ComputeLibrary/files/1718839/normTestsetup.txt)

Thanks,

**Comment by giorgio-arena** [comment] 2018-02-19 16:40
Hi @nhkrishna 

I've reproduced your example using the value you provided and I got the same results, so you should not be doing anything wrong.
Could you please tell us where you got these "expected" result values from, in order to understand whether this is actually a bug or not?!

Thanks

**Comment by nhkrishna** [comment] 2018-02-20 05:37
When I say expected results, I mean the results that I have obtained for MNIST using CuDNN library on Nvidia GPU. These results also match with Intel MKL-DNN  library on a desktop and both are working fine for MNIST Network. But, with ARM ComputeLibrary I am getting mismatch in results at NormLayer output as compared to these libraries.

**Comment by GeorgeARM** [comment] 2018-02-20 11:27
Hello @nhkrishna,

I think that the problem is in the model you have defined or a mismatch of how we interpret the `FullyConnectedLayer`.
If in your example change the shape to `TensorShape(1U, 1U, 500U)` you will get the correct result.
What you are doing now is performing cross map LRN is a row vector which from the expected results isn't what you want.

**Comment by nhkrishna** [comment] 2018-02-21 14:23
Hello @GeorgeARM ,

I've changed the shapes of both `src` and `dest` tensors to `TensorShape(1U, 1U, 500U)`  in my test file. But still i'm seeing the wrong result. I've attached the modified testfile and its output for your reference.

[normTestSetup.txt](https://github.com/ARM-software/ComputeLibrary/files/1744287/normTestSetup.txt)
[normOutput_io.txt](https://github.com/ARM-software/ComputeLibrary/files/1744275/normOutput_io.txt)

If you got the correct result,  Let me know the test file that you have written . 

Thanks

**Comment by GeorgeARM** [comment] 2018-02-21 14:44
@nhkrishna you cannot use memcpy anymore to fill your tensor, thus use a window loop instead.
Now the NormLayer function will add padding spatially as it process 4 elements across width each time and your width is 1, thus it should add a padding of 3.

**Comment by nhkrishna** [comment] 2018-02-22 10:29
Hello @GeorgeARM ,

Finally i got the correct results. But, after configure sizes of `src` and `dst` tensor are increased to `8000` and `2000` respectively. We know that embedded devices have some  memory constraints. So, if sizes are increasing in this way embedded application will consumes lot of memory.

Is there any idea to retain the sizes of  `src` and `dst` tensors after configure.

Thanks

**Comment by GeorgeARM** [comment] 2018-02-22 10:37
Hello @nhkrishna,
Yes it will increase your size. What you could do probably is to think it the other way around.
Meaning you could leave your shape as `TensorShape(500U)` and do an `IN_MAP` normalization with the same parameters. This shouldn't add much padding. Give it a try.

**Comment by GeorgeARM** [comment] 2018-02-26 12:09
Closing this issue. Reopen if needed.

**Closed by GeorgeARM** 2018-02-26 12:09 UTC
