### ISSUE TITLE
Non Maximal ACL kernel GPU output mismatch with NEON output - Request for inputs (ACL v.17.10)

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#418] opened 2018-04-09 07:49 UTC
Hi Sir, 

When executing Non Max supression kernel, Outputs of GPU and NEON  is not matching. NEON output is matching with OpenVx reference C Model implementation. 

Version : 17.10 . 

Attaching the Standalone workspace, logs for reference. 

Can you please help in resolving this issue?? 

Thanks,
Vinith 
[nonmaxsuppression_neon_16x16_output.txt](https://github.com/ARM-software/ComputeLibrary/files/1888863/nonmaxsuppression_neon_16x16_output.txt)
[cl_nonmax_suppression_standalone+ouptut.txt](https://github.com/ARM-software/ComputeLibrary/files/1888864/cl_nonmax_suppression_standalone.ouptut.txt)
[cl_NonMaxSuppression_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1888865/cl_NonMaxSuppression_api.txt)
[non_maximum_suppression_neon_gpu_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1888867/non_maximum_suppression_neon_gpu_log.txt)

**Comment by manjunathahg** [comment] 2018-06-25 11:12
Hello team,
Any update on the above issue?

**Comment by AnthonyARM** [comment] 2018-06-25 12:09
Hi,
No update: the reproduction case provided doesn't allow to reproduce the issue. (The logs attached say the image doesn't match the reference output, but there is no reference implementation provided)
We've added in 18.05 validation tests for Harris Corners that use non maxima suppression and as far as we know the function works.

**Comment by morgolock** [comment] 2018-08-15 14:45
Hi @vinithsrvv1 

I wrote a test and I couldn't reproduce the mismatches, please try again with the latest version of the library 18.05.


![nonmax](https://user-images.githubusercontent.com/5577511/44154248-3100722a-a0a2-11e8-90e2-6d2f39bdde82.png)

Closing the issue, please reopen if you still have mismatches.

**Closed by morgolock** 2018-08-15 14:45 UTC
Labels: Question
