### ISSUE TITLE
"Tensor dimensions mismatch" Error

### ISSUE THREAD

**Issue by zhaofenqiang** [ARM-software/ComputeLibrary#354] opened 2018-02-08 05:19 UTC
I wanted to run examples/graph_mobilenet to classify images.
So firstly I converted the pre-trained MobileNet_v1_1.0_224 model [here](https://github.com/tensorflow/models/tree/master/research/slim) by tensorflow_data_extractor.py,  due to this [issue](https://github.com/ARM-software/ComputeLibrary/issues/324), I converted the pre-trained model by tensorlfow's NewCheckpointReader in this [example](https://github.com/tensorflow/tensorflow/blob/f7f7036d1cdc5716aff976fae0ea4d1b9a931b56/tensorflow/python/tools/inspect_checkpoint.py#L48).

And the extracted first layer weight's shape is like [3 3 3 32], fortran_order is false, and the required tensor' shape is [3 3 3 32], so it will encounter the error [here](https://github.com/ARM-software/ComputeLibrary/blob/f45d5a9be1bf4d315a227b80617582b8eb4214d2/utils/GraphUtils.cpp#L347). 

So I converted the C_order to fortran_order before `np.save(varname, numpy_array)` by `np.asfortranarray()`,the error is gone, but the classified result "Top 5 predictions" is wrong.

I think the problem is loading model's weight mistakenly, and the details of loading weights is a little complicated for me. I am confused about this loading process, any suggestion could be very helpful, thank you!

**Comment by zhaofenqiang** [comment] 2018-02-08 06:54
I am not very sure if this is a bug.
I found examples/graph_mobilenet load BatchNorm_beta and BatchNorm_gamma in this [way](https://github.com/ARM-software/ComputeLibrary/blob/f45d5a9be1bf4d315a227b80617582b8eb4214d2/examples/graph_mobilenet.cpp#L102)  
`<< BatchNormalizationLayer(
                  get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_moving_mean.npy"),
                  get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_moving_variance.npy"),
                  get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_beta.npy"),
                  get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_gamma.npy"),
                  0.001f)`

But the BatchNormalizationLayer constructor accept parameter like this [here](https://github.com/ARM-software/ComputeLibrary/blob/f45d5a9be1bf4d315a227b80617582b8eb4214d2/arm_compute/graph/nodes/BatchNormalizationLayer.h#L50):
`BatchNormalizationLayer(AccessorType &&mean, AccessorType &&var, AccessorType &&gamma, AccessorType &&beta, float epsilon)
        : _mean(std::move(mean)), _var(std::move(var)), _gamma(std::move(gamma)), _beta(std::move(beta)), _epsilon(epsilon)
    {
    }`

As you can see, the gamma and beta is disordered.
Nevertheless, after changing the order,  the "Top 5 predictions" is still wrong, I can't figure out other causes, can anyone give me some help, thanks!~

**Comment by GeorgeARM** [comment] 2018-02-09 11:02
Hello @zhaofenqiang,

We have resolved all issues on mobilenet graph example and will be part of the next release.
The gamma and beta issue is one of them along with the way of parsing the trainable parameters.
Is this something urgent for you or you can wait for the next release in a couple of weeks?

**Comment by zhaofenqiang** [comment] 2018-02-10 04:16
@GeorgeARM , thank you for your reply, actually it's not very urgent, I can wait for the next release, and thank you guys for your contributions.

**Comment by GeorgeARM** [comment] 2018-02-26 12:07
Resolved in 18.02. Reopen if needed

**Closed by GeorgeARM** 2018-02-26 12:07 UTC
Labels: Fixed in next release

**Comment by santo4ul** [comment] 2018-07-25 14:37
I'm trying to run the examples/graph_mobilenet and facing a different problem. Could someone thorw some light?

I don't have a GPU. On my Ubuntu 16.04, installed tensorflow 1.9.0 CPU  version using pip (as per [here](https://www.tensorflow.org/install/install_linux) 

My tensorflow is installed correctly, 

$ python3 -c "import tensorflow as tf; print(tf.__version__)"
1.9.0

Downloaded mobilenet_v1_1.0_224 from [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md) and based on instructions from [here](https://arm-software.github.io/ComputeLibrary/latest/data_import.xhtml#tensorflow_data_extractor) I'm trying to extract data. However, I get the following error (Cannot assign a device... ), I tried setting export CUDA_VISIBLE_DEVICES="" as suggested by many people online, but it doesn't seem to work, 

san@san-Thinkpad-T440S:~/san/ComputeLibrary$  python3 ./scripts/tensorflow_data_extractor.py -m mobilenet_v1_1.0_224 -n examples/cnn_data/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt.meta
2018-07-25 20:03:30.067575: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/tensorflow_data_extractor.py", line 42, in <module>
    saver.restore(sess, args.modelFile)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

Caused by op 'parallel_read/filenames/Greater', defined at:
  File "./scripts/tensorflow_data_extractor.py", line 39, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3563, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3563, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3450, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

Thank you.
