### ISSUE TITLE
Deconvolution layer with armnnCaffeParser.

### ISSUE THREAD

**Issue by kuladeep2706** [ARM-software/ComputeLibrary#523] opened 2018-08-21 08:29 UTC
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
arm64-v8a

**Operating System:**
Android Oreo

**Problem description:**
I am trying to run deconvolution layer of caffe using armnn through Compute Library (CL Kernel).
I have added Parsing code for deconvolution in armnnCaffeParser. When I am running the deconvolution kernel through armnn, it is taking ~500ms and the answer is also not matching to the output of deconvolution layer in caffe. Now my questions are as follows.
1. Can I pass the weights obtained from caffe's deconv layer as it is without any modification to arm compute deconv's configure, or any transformation of weights is required?
2. I have tried weights transformations mentioned in previous issues like flipping around WxH plane & transposing the weights. But they didn't work.
3. I have also applied inner_border patch, still there is no change since inner_border_right & inner_border_top are same in our case.

Hoping to get pointers in the right direction for this.
Thanks in advance!

**Comment by mpekatsoula** [comment] 2018-08-21 08:57
Hi @kuladeep2706 

Could you please share the tensor shapes used in deconvolution layer and also the vale of the inner border?
Also, the weights used in Deconvolution should be in the following format: [W, H, IFM, OFM]

**Comment by kuladeep2706** [comment] 2018-08-21 08:59
Hi @mpekatsoula 
Inner border values are 4, 4 in my case. Tensor shapes for deconvolution layer are [4, 4, 16, 3].

**Comment by mpekatsoula** [comment] 2018-08-21 09:11
Inner border set to 4 seems a bit too much so, lets make sure you use the correct value.

The formula for computing the output shape is:
o = s*(i - 1) + a + k - 2*p

k: kernel size
s: stride
i: input size
o: output size
p: padding
a: inner border

Since we know the output shape, it's easy to calculate the value of a. Please double check if that's the case or else we'll need also the input/output shapes (just the shapes), padding and stride values in order to reproduce the test in our side.

**Comment by morgolock** [comment] 2018-08-21 09:15
Hi @kuladeep2706 

Could you please try to reduce the shape to something like [4,4,2] (smaller easier to debug) and share all the input arguments you are passing to deconvolution.configure() as well as the output of ACL, the reference values and the weights?

This might help to understand where the problem is.

**Comment by kuladeep2706** [comment] 2018-08-21 09:27
Hi @mpekatsoula,
For weights tensor, is it sufficient to just reshape the weight blob that I get from caffe into [W, H, IFM, OFM] or should I apply any transformations on it? Some issues prior to this were mentioning flipping over WXH plane. 
Also, I was setting output shape as o = s*(i - 1) + k - 2*p before, I will rectify this and mention the results.

Hi @morgolock,
I will write a validation test with a smaller output and mention the results.

Thanks.

**Comment by kuladeep2706** [comment] 2018-08-21 10:45
Hi @mpekatsoula,
Can you confirm whether inner_border_right = dilation_data[0]*(this.kernel_shape.cpudata()[0]-1) + 1 as in caffe?
Using this I get the value as 4.

**Comment by mpekatsoula** [comment] 2018-08-22 08:59
Hi @kuladeep2706 

If I remember correctly caffe uses a different implementation, so the inner border should arrive from the formula I posted earlier.

**Comment by mpekatsoula** [comment] 2018-09-03 08:43
HI @ssj4gogeta 

Is it possible to share a simple example that reproduces your issue, alongside with the expected result?

Thanks

**Comment by mpekatsoula** [comment] 2018-09-17 10:32
Closing, reopen if needed.

**Closed by mpekatsoula** 2018-09-17 10:32 UTC
Labels: Question
