### ISSUE TITLE
Error in Cross Compiling example C++ codes

### ISSUE THREAD

**Issue by d-b-h** [ARM-software/ComputeLibrary#614] opened 2019-01-10 05:08 UTC
**Output of 'strings libarm_compute.so | grep arm_compute_version** - 
arm_compute_version=v18.11 Build options: {'embed_kernels': '1', 'opencl': '1', 'neon': '1', 'internal_only': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=3d2d44ef55ab6b08afda8be48301ce3c55c7bc67

**Platform** - x86_64
**Operating System** - Ubuntu 16.04

**Problem description:**
I am trying to cross compile a C++ script using g++-aarch64-linux-gnu compiler. When i run the following command to compile an example script given in ComputeLibrary/examples 

aarch64-linux-gnu-g++ examples/neon_cartoon_effect.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -mfpu='neon' -L/home/deeptihegde/ComputeLibrary/build  -larm_compute -o build/neon_cartoon_effect

I get the following error:

aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-mfpu=neon’

If i drop that tag, errors get thrown for all my NEON functions.

Am I using the wrong compiler?

**Comment by d-b-h** [comment] 2019-01-10 11:05
hi @mpekatsoula 
thanks for you reply. I added the -larm_compute_core tag and removed the -mfpu='neon' tag and i got the below message:

/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/cc4wW5Nw.o: undefined reference to symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcN9__gnu_cxx17__normal_iteratorIPKcS4_EESA_@@GLIBCXX_3.4.21'
//usr/aarch64-linux-gnu/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by mpekatsoula** [comment] 2019-01-10 12:01
What is the version of your compiler? Can you try with -lstdc++ ? Also place all your link flags in the end of the command line: 
`aarch64-linux-gnu-g++ examples/neon_cartoon_effect.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -o build/neon_cartoon_effect  -L/home/deeptihegde/ComputeLibrary/build -larm_compute -larm_compute_core`

**Comment by d-b-h** [comment] 2019-01-10 12:17
It compiled! Now the executable is in my build folder. However, when I try to run it on my arm device (aarch64, armv8-A snapdragon 636) it says "no such file", whereas it runs the example executables just fine

**Comment by mpekatsoula** [comment] 2019-01-10 12:20
Great! Closing this as the problem now is a duplicate of https://github.com/ARM-software/ComputeLibrary/issues/615

**Closed by mpekatsoula** 2019-01-10 12:20 UTC
Labels: Help wanted
