### ISSUE TITLE
Cannot get correct TanH result

### ISSUE THREAD

**Issue by cyberfire** [ARM-software/ComputeLibrary#77] opened 2017-04-28 14:43 UTC
@AnthonyARM I try to use TanH function provided in ACL, but I cannot get the correct result.
Would you please help to check this small test case and help me?
<code>
int main(int argc, char * argv[]) {
    
    unsigned int number=10;

    ActivationLayerInfo activation_info(ActivationLayerInfo::ActivationFunction::TANH,1.0,1.0);

    TensorShape iShape(number);
    TensorShape oShape(number);
    
    Tensor iTensor,oTensor;
 
    iTensor.allocator()->init(TensorInfo(iShape, Format::F32));
    oTensor.allocator()->init(TensorInfo(oShape, Format::F32));
    
    NEActivationLayer layer;
    layer.configure(&iTensor,&oTensor, activation_info);

    iTensor.allocator()->allocate();
    oTensor.allocator()->allocate();

    float * input=(float *)iTensor.buffer();

    for(int i=0;i<number;i++) input[i]=i*10;

    cout<<"iTensor content:..."<<endl;
    iTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

    layer.run();
    
    cout<<"oTensor content:..."<<endl;
    oTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

}
</code>
The output is as follows, which is definitely wrong.
iTensor content:...
 0 10 20 30 40 50 60 70 80 90 

oTensor content:...
     0      1      1      1      1     -1     -1     -1     -1 1.1686 

Thanks,

Cyberfire

**Comment by AnthonyARM** [comment] 2017-04-28 19:28
I think the issue is that you're writing in the padding : `buffer()` returns a pointer to the start of the allocation, not the first element of the buffer.
You need to add `input.info()->offset_first_element_in_bytes()`

**Comment by AnthonyARM** [comment] 2017-04-28 19:29
If that's not the issue could you please share the content of your print function? (You seem to have a lot of integers printed for some reason)

**Comment by AnthonyARM** [comment] 2017-04-28 19:52
Ok, I managed to reproduce the issue, we'll have a look soon and we'll let you know

**Comment by gmiodice** [comment] 2017-05-01 12:47
HI @cyberfire ,

we have found the issue and it seems within the function vtan_f32 https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/NEON/NEMath.h#L165 . In that function the variable "val" should be clamped before passing it to vexp_f32 https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/NEON/NEMath.h#L170.

This issue should be fixed with the next release.

Many thanks for providing the test and for reporting the issue.

**Comment by cyberfire** [comment] 2017-05-02 16:32
@gmiodice 
Could you please post a small patch here, so that I can make it work? as I'm not familiar with NEON programming and  do not get your points:-(

Thanks,
Cyberfire

**Comment by GeorgeARM** [comment] 2017-05-03 12:22
Hello @cyberfire,

I presume if you replace the existing tanh implementation with it should work,
```cpp
/** Calculate hyperbolic tangent.
 *
 * tanh(x) = (e^2x - 1)/(e^2x + 1)
 *
 * @note We clamp x to [-5,5] to avoid overflowing issues.
 *
 * @param val Input vector value in F32 format.
 *
 * @return The calculated Hyperbolic Tangent.
 */
inline float32x4_t vtanhq_f32(const float32x4_t &val)
{
    static const float32x4_t CONST_1        = vdupq_n_f32(1.f);  // 1.f
    static const float32x4_t CONST_2        = vdupq_n_f32(2.f);  // 2.f
    static const float32x4_t CONST_MIN_TANH = vdupq_n_f32(-5.f); // -5.f
    static const float32x4_t CONST_MAX_TANH = vdupq_n_f32(5.f);  // 5.f

    float32x4_t x     = vminq_f32(vmaxq_f32(val, CONST_MIN_TANH), CONST_MAX_TANH);
    float32x4_t exp2x = vexpq_f32(vmulq_f32(CONST_2, x));
    float32x4_t num   = vsubq_f32(exp2x, CONST_1);
    float32x4_t den   = vaddq_f32(exp2x, CONST_1);
    float32x4_t tanh  = vmulq_f32(num, vinvq_f32(den));
    return tanh;
}
```
Try it out and let me know.

George

**Comment by cyberfire** [comment] 2017-05-04 06:04
@GeorgeARM 
This patch can work, just have one issue : there are no vexpq_f32 and vinvq_f32  in ver 17.04.
So that I uses vexp_f32 and vinv_f32 instead.
Also, it seems a little bit too aggressive to clamp to 5, and I changed to 10.

Here is the version passed tests:

/** Calculate hyperbolic tangent.
 *
 * tanh(x) = (e^2x - 1)/(e^2x + 1)
 *
 * @note We clamp x to [-10,10] to avoid overflowing issues.
 *
 * @param val Input vector value in F32 format.
 *
 * @return The calculated Hyperbolic Tangent.
 */
inline float32x4_t vtanh_f32(const float32x4_t &val)
{
    static const float32x4_t CONST_1        = vdupq_n_f32(1.f);  // 1.f
    static const float32x4_t CONST_2        = vdupq_n_f32(2.f);  // 2.f
    static const float32x4_t CONST_MIN_TANH = vdupq_n_f32(-10.f); // -10.f
    static const float32x4_t CONST_MAX_TANH = vdupq_n_f32(10.f);  // 10.f

    float32x4_t x     = vminq_f32(vmaxq_f32(val, CONST_MIN_TANH), CONST_MAX_TANH);
    float32x4_t exp2x = vexp_f32(vmulq_f32(CONST_2, x));
    float32x4_t num   = vsubq_f32(exp2x, CONST_1);
    float32x4_t den   = vaddq_f32(exp2x, CONST_1);
    float32x4_t tanh  = vmulq_f32(num, vinv_f32(den));
    return tanh;
}

Thanks,

Cyber

**Comment by GeorgeARM** [comment] 2017-05-04 09:21
Closing as fix is committed. If clamping between [-5,5] causes issues reopen to increase the constants.

**Closed by GeorgeARM** 2017-05-04 09:21 UTC
Labels: Bug, Fixed in next release
