### ISSUE TITLE
Half scale gaussian kernel GPU output mismatch - 5x5 kernel ACL version 17.10 - request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#423] opened 2018-04-09 13:10 UTC
Hi Sir,

When executing Half scale gaussian kernel in ACL GPU, output mismatches with NEON output. NEON  is matching with reference  OpenVx implementation . Attaching the logs, sample workspace for reference .

Can you please help in resolving this issue?

Thanks,
Vinith 
[cl_halfscale_gaussian_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1889997/cl_halfscale_gaussian_api.txt)
[neon_halfscalegaussian_output.txt](https://github.com/ARM-software/ComputeLibrary/files/1889998/neon_halfscalegaussian_output.txt)
[cl_halfscale_gaussian_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1889999/cl_halfscale_gaussian_log.txt)

**Comment by AnthonyARM** [comment] 2018-04-09 13:27
Seems to be a problem with your OpenCL driver, not an issue with the library:

```
cl_halfscalegaussian: /usr/src/debug/adreno/1.0+git-r0/graphics/adreno200/llvm/lib/Target/Oxili/QGPUTargetObjGen.cpp:933: virtual bool llvm::QGPUModuleEncoder::runOnModule(llvm::Module&): Assertion `0 && "The total instruction number in CreateLabelPass does not match the total number after CodeGen"' failed.
```

**Comment by psyhtest** [comment] 2018-04-17 13:33
@vinithsrvv1 I wouldn't expect the Arm Compute Library written for Arm Mali GPUs to play well with Qualcomm Adreno GPUs. Any reason you are trying that?

**Comment by vinithsrvv1** [comment] 2018-04-17 13:36
We are working on the customer project which we needed to use this. So you are telling this is the problem with the driver of the Adreno  ?

**Comment by AnthonyARM** [comment] 2018-04-17 14:32
As far as we know our OpenCL kernels are OpenCL compliants, so it *should* run on Adreno. (Performance is unlikely to be good though).

**Comment by psyhtest** [comment] 2018-04-20 14:57
@AnthonyARM Oh, I do not question OpenCL compliance of Arm CL kernels (apart of occasional use of Arm specific extensions such as `cl_arm_non_uniform_work_group_size`). 

It's more about OpenCL compliance of Adreno drivers. If you look at [GraphicsFuzz results](http://www.graphicsfuzz.com/results/all.html), Qualcomm devices are at the very bottom. And those are recent devices (2017) with Adreno 5xx series. @vinithsrvv1 's device seems to be based on Adreno 2xx?

**Comment by psyhtest** [comment] 2018-04-20 14:58
Actually, according to [Wikipedia](https://en.wikipedia.org/wiki/Adreno), Adreno 2xx is not OpenCL capable at all?

**Comment by morgolock** [comment] 2018-08-15 14:15
Closing the issue is the same as: https://github.com/ARM-software/ComputeLibrary/issues/422#issuecomment-413154346

**Closed by morgolock** 2018-08-15 14:15 UTC
Labels: Duplicate, Question
