### ISSUE TITLE
huge memory consumption during configure

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#801] opened 2020-02-04 09:33 UTC
Hi,

I am seeing a huge memory consumption (~ 1.3GB) while configuring NEDeconvolutionlayer.
inputSize 30 x 40 x 256 and weights 8 x 8 x 256 x 256.

Why is this happening?

Thanks,
Pranathi.

**Comment by morgolock** [comment] 2020-02-05 17:01
Hi @pranathibl 

Could you please share all the values you use to configure the function? Data types and PadStrideInfo ?

**Comment by pranathibl** [comment] 2020-02-06 04:40
Hi @morgolock 

I have attached the setup i have used [here](https://github.com/ARM-software/ComputeLibrary/files/4163224/transposed_standalone.zip)

**Comment by sanpar02** [comment] 2020-02-06 14:19
Hi @pranathibl.

Thanks for the setup and I could reproduce the issue with the setup.
From investigation, I found this is expected behavior on NEON mainly due to the Im2col. We'll start our internal discussion to plan the improvement. 

As an alternative for now, if you can use OpenCL version of DeconvolutionLayer, it is expected to have smaller memory consumption.

I hope it helps.

**Comment by ManubARM** [comment] 2020-05-19 10:31
Hi @pranathibl ,
We recently merged a patch which should solve your problem. 
This is the line you might be more interested on:
https://review.mlplatform.org/c/ml/ComputeLibrary/+/3135/6/src/runtime/NEON/functions/NEConvolutionLayer.cpp#170

Basically we pick NEDirectConvolution in case of big input tensors and bigger weights shapes to avoid the need of huge allocations. In fact, this layer doesn't require more memory

Let us know,
Manuel

**Comment by pranathibl** [comment] 2020-07-07 16:34
Hi @ManubARM ,

I have tried out with the patch provided. and still seeing the memory consumption to be high (1.3GB).

Thanks,
Pranathi.

**Comment by ManubARM** [comment] 2020-07-07 16:58
Could you please try to print what are your values of:
input->total_size()  and weights->dimension(idx_h) 
?
And also which ConvolutionMethod is get_convolution_method() returning?

Best,
Manuel

**Comment by pranathibl** [comment] 2020-09-01 16:13
Hi @ManubARM ,

It is picking GEMM as Convolution method.
And input->total_size() = 21.7MB
weights->dimension(idx_h) = 8

-Pranathi

**Comment by morgolock** [comment] 2021-12-09 10:27
Hi @pranathibl 

The following patch on the top of master solves the problem:  https://review.mlplatform.org/c/ml/ComputeLibrary/+/6806

I ran the test and it's now using DirectConv as Deconvolution method. 

Hope this helps.

**Closed** 2021-12-20 12:39 UTC
Labels: Question, Feature Request, MLCE
