### ISSUE TITLE
Is GEMM library optimized for bifrost architecture of Mali GPU?

### ISSUE THREAD

**Issue by atrah22** [ARM-software/ComputeLibrary#186] opened 2017-07-25 10:59 UTC
Hello, 
I posted a similar question for previous release of ACL (https://github.com/ARM-software/ComputeLibrary/issues/70) and the reply to that was the previous release was not optimized for bifrost architecture.

So my question is same again. Is the GEMM library not optimized for Bifrost architecture yet?

I see similar result in this release (17.06) aswell on Galaxy S8 (Bifrost architecture GPU) vs Galaxy S7 (Midgrad architecutre GPU).

For FP32 precision and GoogleNet Dataset1 + Dataset2 (ran the GEMM test from benchmark folder), the results are:
S7 --> 151 ms
S8 --> 157 ms
For FP16 precision and GoogleNet Dataset1 + Dataset2, the results are:
S7 --> 118.07 ms
S8 --> 126.05 ms

However, it is shown on page 15 in the ARM Compute Library webinar ( https://www.youtube.com/watch?v=xwESWqdJt_Y ) that the Huawei Mate 9 (bifrost) has better performance than Huawei P9 (Midgrad) incase of OpenCL kernel!

**Comment by gmiodice** [comment] 2017-07-25 11:15
Hi @atrah22 ,

quick question for trying to reproduce the result. Could you please share the build command used for the Compute Library?

Many thanks in advance

**Comment by AnthonyARM** [comment] 2017-07-25 15:02
Hi,

The P9 has a T880 MP4 @ 900 MHz
Mate 9 has G71 MP8 @ 1037 MHz

S7 has T880 MP12 @ 650 Mhz
S8 has G71 MP20 @ 550 MHz

As you can see the S7 and S8 are clocked lower than the Huawei devices, also, if the workloads are too small (As it's sometimes the case with neural network layers) then not all the GPU cores will be busy (In which case a GPU with fewer cores and a higher frequency would probably go faster).

Hope this helps,

Anthony

**Comment by atrah22** [comment] 2017-07-26 02:30
@gmiodice, The build command is shown below:
/data/local/tmp/arm_compute_benchmark_CL --benchmark_format=json /data/local/tmp/data/ --benchmark_filter=GEMMFP16GoogLeNet1 --benchmark_report_aggregates_only=true --thread=8

For 2nd Dataset, I just change the benchmark_filter to GEMMFP16GoogLeNet2. 

@AnthonyARM, Thankyou for your clear reply.

**Comment by Jothi-PM** [comment] 2017-10-11 07:43
@AnthonyARM , Is it possible to test Mali G71 MP8 GPU?  I'm not able to use that GPU on Huawei P10.
Facing clGetPlatformIDs failed?

**Comment by AnthonyARM** [comment] 2017-10-11 08:13
Unfortunately we don't have a P10 in the office so I can't reproduce, what error / string does the clGetPlatformIDs return ?
Are you sure your OpenCL driver otherwise works ?

**Comment by Jothi-PM** [comment] 2017-10-11 08:31
Number of OpenCL platforms returned is 0 always. Is it possible to use arm compute OpenCL library at run time too? I guess P10 vendor OpenCL is not a public library. does linking arm compute OpenCL library detect GPU?

**Comment by AnthonyARM** [comment] 2017-10-11 08:43
That's odd it returns 0.
What do you mean by "use at run time" ? 
The Compute Library does a dlopen of libOpenCl.so and then try to detect the GPU based on what clGetDeviceInfo returns, but the application can override that by manually setting the GPU using [CLScheduler::set_target()](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/arm_compute/runtime/CL/CLScheduler.h#L142)

**Comment by Jothi-PM** [comment] 2017-10-11 09:27
[](https://arm-software.github.io/ComputeLibrary/v17.09/#S3_3_android)
I referred the above link for building ARM compute library. In that page, its mentioned that OpenCL stub library is for resolving symbols while building applications. To load it dynamically we need to have real OpenCL.so. does it mean that we cannot use arm compute OpenCL while running our application and we need to give a path to the real OpenCL library?

**Comment by AnthonyARM** [comment] 2017-10-11 09:38
The library will try to open [different libraries](https://github.com/ARM-software/ComputeLibrary/blob/v17.09/src/core/CL/OpenCL.cpp#L40), your libOpenCL.so just need to be in your path.
However since [Android 7.0](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk) the libOpenCL.so needs to be white listed by the OEM (In your case Huawei) if you want to be able to use it in an App and I don't think they currently do it.
The alternative is to target an API level of 23 or lower for your app

**Comment by Jothi-PM** [comment] 2017-10-11 09:51
@AnthonyARM , Thank you. P10 has Android 7.0 and Huawei doesn't have its OpenCL as a public library. Much clear now.

**Comment by Jothi-PM** [comment] 2017-10-11 10:29
I tried simple C++ program (compiled as executable not .apk) with OpenCL on android. It works fine. I wonder how executable can access mobile OpenCL and the app cannot. Does rooting the mobile clear the air to access private library on Android 7.0?

**Comment by arunponnusamy** [comment] 2017-10-13 12:14
Hi @atrah22 , Did you try using OpenCL on an Andriod app on S8 ? 
Were you able to run OpenCL Info / OpenCL Z app on S8? Did it show the OpenCL version ? Basically, is OpenCL library public on S8 so that we can use it on Android app ?

**Comment by arunponnusamy** [comment] 2017-10-13 12:26
Hi @gmiodice , in this [issue](https://github.com/ARM-software/ComputeLibrary/issues/70) you have mentioned that CLGEMM (both fp32 and fp16) has not been optimized for Mali Bifrost architectures. It will be helpful to know the current status. Is it optimized for Bifrost architecture (Mali G71) ?

 Also I would like to know how does it compare with OpenCV GEMM on Android with Mali G71 GPU ? Will replacing OpenCV GEMM on an Android app with ARM compute library CL GEMM yield better performance ? Is there any benchmarking you have done against OpenCV ?

**Comment by gmiodice** [comment] 2017-10-16 07:31
Hi @arunponnusamy,

we are in the process of adding new kernels optimized for Bifrost architectures. Already in release 17.09 we added new kernels for accelerating convolution layer when the weights have size 1x1, 3x3 and 5x5. In particular, for this specific case, we added [CLDirectConvolutionLayer](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLDirectConvolutionLayer.h) which works at the same manner of CLConvoluionLayer but should have better performance on Bifrost when the weights are 1x1, 3x3 and 5x5. You can find more information [here](https://community.arm.com/graphics/b/blog/posts/announcing-the-compute-library-17-9)

In release 17.09 we also added another key block for accelerating further OpenCL kernel. [CLTuner](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/CLTuner.h).
CLTuner is able to find the optimal LWS for your kernel in order to improve the performance further.

In order to use CLTuner, you need to pass the pointer to your CLTuner object when you call the default_init() method of CLScheduler:
i.e.
CLTuner cl_tuner
CLScheduler::get().default_init(&cl_tuner);
CLKernelLibrary::get().set_kernel_path("./cl_kernels/"); 


Note: **The first run will be much slower** than before because the engine will look for the optimal LWS. 

Hope this can help you,
Gian Marco

**Comment by arunponnusamy** [comment] 2017-10-16 07:49
Thanks for the reply @gmiodice . Any info about the ACL cl gemm performance against OpenCV gemm / blas gemm on Mali GPU?

**Comment by GeorgeARM** [comment] 2018-10-15 13:33
Closing this issue as its really old and seems to have been resolved.

**Closed by GeorgeARM** 2018-10-15 13:33 UTC
Labels: Question
